os: linux
dist: focal
group: edge
language: generic
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - aria2
      - zstd
      - xz-utils
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 2>/dev/null
  - docker pull fr3akyphantom/droid-builder:latest
before_script:
  - sudo snap install git-repo
  - cd $HOME && mkdir twrp
  - cd $HOME/twrp/
  - git config --global user.name juic3b0x
  - git config --global user.email ryn.anthony.garcia@gmail.com
  - git config --global color.ui false
  - repo init -u git://github.com/SHRP/manifest.git -b v3_11.0
  - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
script:
  # Replace your juic3b0x, shrp_android_device_samsung_gta4lwifi, ${_VENDORNAME_}, gta4lwifi
  - cd $HOME/twrp/ && git clone https://github.com/juic3b0x/shrp_android_device_samsung_gta4lwifi
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/builder/twrp/:rw,z" -v "${HOME}/.ccache:/srv/ccache:rw,z" fr3akyphantom/droid-builder bash << EOF
    cd /home/builder/twrp/
    source build/envsetup.sh
    # Choose build flavor as "eng" or "userdebug"
    BUILD_FLAVOR="eng"
    lunch twrp_gta4lwifi-eng
    make -j$(nproc --all) recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/gta4lwifi/recovery.img $HOME/twrp/TWRP-$version-gta4lwifi-$(date +"%Y%m%d")-Unofficial.img
  - cd $HOME/twrp/
  # Optional: You might need to switch from https://transfer.sh to https://file.io
  # - curl -s --upload-file TWRP-$version-gta4lwifi-$(date +"%Y%m%d")-Unofficial.img https://transfer.sh/ && echo ""
deploy:
  provider: releases
  # The secret api_key will be loaded from the environment variables
  token: $GitOAUTHToken
  cleanup: false
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: juic3b0x/shrp_android_device_samsung_gta4lwifi
    branch: android-11
branches:
  only:
    - android-11 # Set travis builder branch(es) names
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
